name: 'dependame'
description: 'A GitHub Action built with .NET'
author: '@yoannchaudet'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  command:
    description: 'Command to execute: EnableAutoMerge, UpdateBranch, BumpPR, or NoOp'
    required: true
  auto_merge_branches:
    description: |
      Target branches for auto-merge. Supports:
      - Single branch: "main"
      - Multiple branches: "main,develop"
      - Glob patterns: "release/*"
      Leave empty to disable auto-merge feature.
    required: false
    default: ''
  auto_merge_method:
    description: 'Merge method for auto-merge: merge, squash, or rebase'
    required: false
    default: 'squash'
  update_branch_label:
    description: |
      Label to apply to PRs after their branch is updated.
      The label is removed from PRs that are behind their base branch.
      Set to empty string to disable labeling.
    required: false
    default: 'ready-for-review'
runs:
  using: 'docker'
  image: 'Dependame/Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.command }}
    - ${{ inputs.auto_merge_branches }}
    - ${{ inputs.auto_merge_method }}
    - ${{ inputs.update_branch_label }}
